package io.github.kazemek.jsonapi.jackson3;

/** Stable diagnostic codes for domain-to-resource mapping failures. */
public enum MappingDiagnostic {
  DUPLICATE_ROLE,
  NAME_COLLISION,
  INVALID_RESOURCE_TYPE,
  INVALID_ATTRIBUTE_NAME,
  INVALID_RELATIONSHIP_NAME,
  MISSING_ACCESSOR,
  MISSING_IDENTIFIER,
  MISSING_RESOURCE_ANNOTATION,
  UNSUPPORTED_ATTRIBUTE_VALUE,
  UNSUPPORTED_RELATIONSHIP_VALUE,
  UNSUPPORTED_RELATIONSHIP_COLLECTION_TYPE,
  INVALID_INCLUDE_PATH,
  DENIED_RELATIONSHIP_INCLUDE,
  CONFLICTING_INCLUDED_REPRESENTATION,
  INCLUDE_DEPTH_EXCEEDED,
  INCLUDE_COUNT_EXCEEDED,
  RESOURCE_TYPE_MISMATCH,
  IDENTIFIER_CONVERSION_FAILED,
  RELATIONSHIP_CARDINALITY_MISMATCH,
  UNSUPPORTED_RELATIONSHIP_TARGET,
  LINKAGE_MAPPING_FAILED,
  MISSING_CREATOR_INPUT,
  UNREGISTERED_RESOURCE_TYPE,
  CONFLICTING_TYPE_REGISTRATION,
  INVALID_FIELDSET_FIELD,
  DENIED_FIELDSET_FIELD,
  FIELDSETS_REQUIRE_MAPPED_DOCUMENT
}
