package io.github.kazemek.jsonapi.jackson3;

/** Stable diagnostic codes for domain-to-resource mapping failures. */
public enum MappingDiagnostic {
  DUPLICATE_ROLE,
  NAME_COLLISION,
  INVALID_RESOURCE_TYPE,
  INVALID_ATTRIBUTE_NAME,
  INVALID_RELATIONSHIP_NAME,
  MISSING_ACCESSOR,
  MISSING_IDENTIFIER,
  MISSING_RESOURCE_ANNOTATION,
  UNSUPPORTED_ATTRIBUTE_VALUE,
  UNSUPPORTED_RELATIONSHIP_VALUE,
  UNSUPPORTED_RELATIONSHIP_COLLECTION_TYPE
}
