package io.github.kazemek.jsonapi.core.validation;

/** Stable rule codes for JSON:API validation failures. */
public enum ValidationRuleCode {
  INVALID_MEMBER_NAME,
  INVALID_URI_REFERENCE,
  INVALID_LINK_RELATION,
  INVALID_LANGUAGE_TAG,
  INVALID_MEDIA_TYPE,
  INVALID_EXTENSION_URI,
  INVALID_PROFILE_URI,
  INVALID_OPEN_JSON_VALUE,
  MEMBER_NAME_COLLISION,
  RESERVED_FIELD_NAME,
  MISSING_RESOURCE_TYPE,
  MISSING_RESOURCE_ID,
  MISSING_ERROR_MEMBER,
  MISSING_RELATIONSHIP_MEMBER,
  MISSING_TOP_LEVEL_MEMBER,
  DATA_ERRORS_COEXIST,
  INCLUDED_WITHOUT_DATA,
  UNKNOWN_ADDITIONAL_MEMBER,
  DISALLOWED_ADDITIONAL_MEMBER,
  DUPLICATE_INCLUDED_RESOURCE,
  FULL_LINKAGE_VIOLATION,
  INCONSISTENT_LOCAL_IDENTIFIER,
  RESOURCE_ID_REQUIRED,
  INVALID_LINKS_CONTEXT,
  RELATIONSHIP_PAGINATION_REQUIRES_HINT
}
